# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-24 17:26
from __future__ import unicode_literals

import apps.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.PositiveIntegerField()),
                ('image1', models.ImageField(upload_to=apps.catalog.models.get_image_path)),
                ('image2', models.ImageField(upload_to=apps.catalog.models.get_image_path)),
                ('image3', models.ImageField(upload_to=apps.catalog.models.get_image_path)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
